
version: '2'
services:
   etcd-node-0:
        image: quay.io/coreos/etcd:v3.1.0
        restart: always
        container_name: etcd-node-0
        volumes:
            - ./etcd-data-0:/etcd-data
        command: /usr/local/bin/etcd  --data-dir=data.etcd  --name etcd-node-0  --initial-advertise-peer-urls http://etcd-node-0:2380 --listen-peer-urls http://etcd-node-0:2380  --advertise-client-urls http://etcd-node-0:2379 --listen-client-urls http://etcd-node-0:2379  --initial-cluster etcd-node-0=http://etcd-node-0:2380,etcd-node-1=http://etcd-node-1:2380,etcd-node-2=http://etcd-node-2:2380  --initial-cluster-state new --initial-cluster-token my-etcd-token
        
   
   etcd-node-1:
        image: quay.io/coreos/etcd:v3.1.0
        restart: always
        container_name: etcd-node-1
        volumes:
            - ./etcd-data-1:/etcd-data
        command: /usr/local/bin/etcd  --data-dir=data.etcd  --name etcd-node-1  --initial-advertise-peer-urls http://etcd-node-1:2380 --listen-peer-urls http://etcd-node-1:2380  --advertise-client-urls http://etcd-node-1:2379 --listen-client-urls http://etcd-node-1:2379  --initial-cluster etcd-node-0=http://etcd-node-0:2380,etcd-node-1=http://etcd-node-1:2380,etcd-node-2=http://etcd-node-2:2380  --initial-cluster-state new --initial-cluster-token my-etcd-token
            
            
   etcd-node-2:
        image: quay.io/coreos/etcd:v3.1.0
        restart: always
        container_name: etcd-node-2
        volumes:
            - ./etcd-data-2:/etcd-data
        command: /usr/local/bin/etcd  --data-dir=data.etcd  --name etcd-node-2  --initial-advertise-peer-urls http://etcd-node-2:2380 --listen-peer-urls http://etcd-node-2:2380  --advertise-client-urls http://etcd-node-2:2379 --listen-client-urls http://etcd-node-2:2379  --initial-cluster etcd-node-0=http://etcd-node-0:2380,etcd-node-1=http://etcd-node-1:2380,etcd-node-2=http://etcd-node-2:2380  --initial-cluster-state new --initial-cluster-token my-etcd-token


